credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "treinee"
          id: "blogger-com3"
          password: "{AQAAABAAAAAwCISKDd+GEw+fD4QGcrCqA7SJT4oOJdrEwRi2dIM3Y2tw7hldw9bgdbqPh8dS7UPuszdU1NZszX642EgLxkYE+Q==}"
          scope: GLOBAL
          username: "abazuntts"
      - usernamePassword:
          description: "treinee"
          id: "blogger-artem"
          password: "{AQAAABAAAAAwgEgITwzJpKkXWJlAzQYD3vT3G6zjEFqD/IpZirhj8++Ri3RERYOpcXO9oYRF6iA6HoHicJgUaW9fFOOY4bk6SQ==}"
          scope: GLOBAL
          username: "abazuntts"
      - usernamePassword:
          description: "treinee"
          id: "blogger-artem123"
          password: "{AQAAABAAAAAwlChuBr0r5M5F6l/dD2euDb9F2ChzDWVRy0FiOiCyVlvm+nBhmBF92GZb8e31zTQiV602OxHYIuTAQYRT862XYA==}"
          scope: GLOBAL
          username: "abazuntts"
      - string:
          id: "abazunts_trainee"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwddDGlQ2GGJysYMPDNLYmkzk7bEyAbAvcE9rS1ldYFfo3ran1ZkXJ/Mr0gsaPXJeGq9HK5DVRr3hC/klcKHsRJg==}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - assignments:
          - "abazunts"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
        - assignments:
          - "jenkins_viewer"
          name: "jenkins_viewer"
          pattern: ".*"
          permissions:
          - "Overall/Read"
        items:
        - assignments:
          - "jenkins_viewer"
          name: "jenkins_viewer"
          pattern: ".*"
          permissions:
          - "Job/Read"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.diagnostics.ControllerExecutorsNoAgents"
  - "org.jenkinsci.plugins.rolestrategy.NamingStrategyAdministrativeMonitor"
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "abazunts"
        name: "Базунц Артем Александровчи"
        properties:
        - "apiToken"
        - mailer:
            emailAddress: "bazunts.a@it-incubator.io"
        - preferredProvider:
            providerId: "default"
      - id: "jenkins_viewer"
        name: "jenkins_viewer"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "bazunts.a@it-incubator.io"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      name: "BLOGGER-ARTEM.COM"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      name: "BLOGGER-ARTEM123.COM"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      jobNames:
      - "prd-blogger-api7-pull-request"
      name: "BLOGGER-COM3.COM"
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  sSHD:
    port: -1
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  ghprbTrigger:
    autoCloseFailedPullRequests: false
    cron: "H/5 * * * *"
    extensions:
    - ghprbSimpleStatus:
        addTestResults: false
        showMatrixStatus: false
    githubAuth:
    - credentialsId: "abazunts_trainee"
      description: "Anonymous connection"
      id: "eaff6c0d-7209-4a9f-9981-1853d0af04a9"
      secret: "{AQAAABAAAAAQViFc28dZOQDwsQQT94Gc97Wh62iPw5dacWZk3UKvqpg=}"
      serverAPIUrl: "https://api.github.com"
    - credentialsId: "abazunts_trainee"
      description: "auth2"
      id: "0b542b91-baa4-4c72-b7cf-8e210645f1c4"
      secret: "{AQAAABAAAAAQWgziaQX9gQdkw8TBhWfVSnyLgHhTTpP44GWZbb93JnE=}"
      serverAPIUrl: "https://api.github.com"
    manageWebhooks: false
    okToTestPhrase: ".*ok\\W+to\\W+test.*"
    requestForTestingPhrase: "Can one of the admins verify this patch?"
    retestPhrase: ".*test\\W+this\\W+please.*"
    skipBuildPhrase: ".*\\[skip\\W+ci\\].*"
    useComments: false
    useDetailedComments: true
    whitelistPhrase: ".*add\\W+to\\W+whitelist.*"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "https://jenkins.trainee.it-incubator.io/github-webhook/"
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  injectionConfig:
    allowUntrusted: false
    enabled: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "адрес еще не настроен <nobody@nowhere>"
    url: "https://jenkins.trainee.it-incubator.io/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
